name: dbt infra CI

on:
  pull_request:
    paths:
      - "dbt_cloud_infra/**"

jobs:
  dbt_terraform:
    name: dbt Infra CI
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ./dbt_cloud_infra

      - name: terraform validate
        uses: dflook/terraform-validate@v2
        with:
          path: ./dbt_cloud_infra