name: CI pipeline

on:
  pull_request:
    paths:
      - "**.sql"
      - "solaz_dbt/**"
      - "dbt_project.yml"

jobs:
  lint:
    name: Lint SQL files
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run SQLFluff
        run: sqlfluff lint solaz_dbt/models/
